application: greek-app
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /(.*\.(gif|png|jpg|ico|js|css|txt|json|woff|ttf|svg|xlxs|csv))
  static_files: \1
  upload: (.*\.(gif|png|jpg|ico|js|css|txt|json|woff|ttf|svg|xlxs|csv))
  secure: always

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  secure: always

- url: /views
  static_dir: views
  secure: always

- url: /picup
  script: main.app
  secure: always

- url: /upload
  script: main.app
  secure: always

# - url: /
#   script: main.app
#   secure: always
- url: /
  upload: index.html
  static_files: index.html
  secure: always

- url: /robots.txt
  static_files: media/robots.txt
  upload: media/robots.txt

- url: /tasks/.*
  script: main.app
  secure: always

- url: /dailynotifications
  script: main.app
  secure: always

- url: /morningtasks
  script: main.app
  secure: always

- url: /_ah/spi/.*
  script: controller.APPLICATION
  secure: always

builtins:
- remote_api: on

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: latest

- name: endpoints
  version: 1.0

- name: pycrypto
  version: latest

- name: PIL
  version: latest

- name: ssl
  version: latest



